[config]
default_to_workspace = false

[tasks.default]
depends = ["format", "lint", "build"]

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.build]
command = "cargo"
args = ["build"]
