[package]
name = "oxidus"
version = "0.1.0"
edition = "2021"
authors = ["Kane Bezadas <kane.bezadas@gmail.com>"]
description = "An internal tf2 cheat"
license = "MIT+"
repository = "https://github.com/PunkSaian/Oxidus"
readme = "../README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
env_logger = "0.11.6"
goblin = "0.9.3"
libc = "0.2.169"
log = "0.4.25"
