[tasks.check]
command = "cargo"
args = ["check"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy-check]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.pre-commit-checks]
description = "Run pre-commit checks: build, fmt, clippy"
dependencies = ["lint", "format", "check"]


[tasks.default]
dependencies = [ "lint", "format","build"]
