[tasks.check]
command = "cargo"
args = ["check"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy-check]
command = "cargo"
args = ["clippy"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--fix"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.pre-commit-checks]
description = "Run pre-commit checks: build, fmt, clippy"
dependencies = ["fmt-check", "clippy-check", "check"]


[tasks.default]
dependencies = ["lint", "format", "build"]
